steps:
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies"
        npm install

  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting application"
        node server.js

timeout: '1200s'